# Generated by Django 5.1.2 on 2024-11-02 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ending_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_ending_station_set', to='BookingApp.trainstation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.passenger'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starting_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.trainstation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='train_journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.trainjourney'),
        ),
        migrations.AlterField(
            model_name='carriageprice',
            name='carriage_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.carriageclass'),
        ),
        migrations.AlterField(
            model_name='journeycarriage',
            name='carriage_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.carriageclass'),
        ),
        migrations.AlterField(
            model_name='journeycarriage',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.trainjourney'),
        ),
        migrations.AlterField(
            model_name='journeycarriage',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.train'),
        ),
        migrations.AlterField(
            model_name='journeystation',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.trainjourney'),
        ),
        migrations.AlterField(
            model_name='journeystation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.trainstation'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.train'),
        ),
        migrations.AlterField(
            model_name='trainjourney',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.train'),
        ),
    ]
